TODOlist/Models/ErrorViewModel.cs
namespace TODOlist.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TODOlist/Models/TODO.cs
public class TODO{
    public int Id {get; set;} 
    public string Tarefa {get; set; } = string.Empty;

    public string Descricao {get; set; } = string.Empty;

    public bool Feito { get; set; } = false;

}

TODOlist/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using TODOlist.Models;

namespace TODOlist.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TODOlist/Controllers/TODOController.cs
using Microsoft.AspNetCore.Mvc;

 
namespace TODOList.Controllers
{
    public class TODOController : Controller
    {
        private readonly dbContext _context;
        public TODOController(dbContext context)
        {
            _context = context;
        }

        List<TODO> TODOs = new List<TODO>   
        {
            new TODO { Id = 1, Tarefa = "Estudar C#", Descricao = "Estudar C# para melhorar o desenvolvimento de aplicações", Feito = false },
            new TODO { Id = 2, Tarefa = "Estudar ASP.NET Core", Descricao = "Estudar ASP.NET Core para melhorar o desenvolvimento de aplicações", Feito = false },
            new TODO { Id = 3, Tarefa = "Estudar Entity Framework", Descricao = "Estudar Entity Framework para melhorar o desenvolvimento de aplicações", Feito = false },
            new TODO { Id = 4, Tarefa = "Estudar Razor", Descricao = "Estudar Razor para melhorar o desenvolvimento de aplicações", Feito = false },
            new TODO { Id = 5, Tarefa = "Estudar MVC", Descricao = "Estudar MVC para melhorar o desenvolvimento de aplicações", Feito = false },
        };
        public IActionResult Index()
        {
            var AllTodos = _context.TODOs.ToList();
            if(AllTodos == null){
                return RedirectToAction("Index", "Home");
            }      
            return View(AllTodos);
        }
        public IActionResult Create(TODO todo){

            var newTodo = new TODO{
                Tarefa = todo.Tarefa,
                Descricao = todo.Descricao,
                Feito = todo.Feito
            };
            _context.TODOs.Add(newTodo);
            _context.SaveChanges();

            return View();
            
        }
    }
}

TODOlist/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <h1><a asp-controller="TODO" asp-action="Index">TODO LIST</a></h1>
</div>

TODOlist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TODOlist</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TODOlist.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TODOlist</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TODOlist - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TODOlist/Views/TODO/Index.cshtml
@{
    ViewData["Tittle"] = "Lista de TODOs";
    var TODOs = (List<TODO>)ViewData["AllTodos"];
}

<h1>List de TODOS!</h1>

<div style="display: flex; flex-direction:row; width: 100vw; flex-wrap: wrap; gap: 5px;">

@{
    foreach (var todo in ViewBag.TODOS)

    {

        <div class="card" style="width: 18rem;">

            <img src="https://lh3.googleusercontent.com/proxy/562me2SdGu8FRjCAw_ZTl9dI_cAkig7q8ei-QVqN-sdlTdTDYdBqXnyPRjXpSesf4w4r0KslDwFLFSjsYTWwIZrjPX2-h7Uv6yKQ1H4G" class="card-img-top" alt="...">

            <div class="card-body">

                <h5 class="card-title">@todo.Tarefa</h5>

                <p class="card-text">@todo.Descricao</p>

                @{

                    if (todo.Feito)

                    {

                        <p class="card-text">Tarefa feita</p>

                    }

                    else

                    {

                        <p class="card-text">Tarefa não feita</p>

                    }

                }
 
            </div>

        </div>
    }
}
</div>